### ISSUE TITLE
JSON Error printImage

### ISSUE THREAD

**Issue by ascattolini** [prakashsatyani/cordova-plugin-bluetooth-zbtprinter#1]
Hi,
I created a phonegap project where I want to load an image form device memory, encode it base64 using "cordova-plugin-base64-joewsh", and then feed the printImage function but obtained JSON error. I don't know what's wrong.
The code I used was:

`var MACAddress="AA:BB:CC:DD:EE:FF";
var base64StringArray="";
window.plugins.Base64.encodeFile("/mnt/sdcard/Pictures/logo.png", function(base64StringArray){
		alert("image encoded: "+base64StringArray.substr(22));
		cordova.plugins.zbtprinter.printImage(base64StringArray, MACAddress,		
			function(success) { 
				alert("Print ok"); 
			    }, function(fail) { 
				alert(fail); 
			    }
			);
	},  function(fail) { 
		alert("fail encode"); 
	    }	
	);
`

**Comment by prakashsatyani** [comment]
Hi @ascattolini,

There was some error in the plugin. I was getting the same error. I have resolved this issue at my end. I will commit the changes soon in the repo.

**Comment by prakashsatyani** [comment]
@ascattolini You need to pass array of base64 string and not the base64 string itself.


Try following:

```
var printImageString = [ base64String ];

cordova.plugins.zbtprinter.printImage(printImageString, MACAddress,
		    function(success) {
		    	
		    }, function(fail) {
		    	
		    }
		);
```

**Comment by ascattolini** [comment]
Thank you very much for your help and for added examples, it worked perfectly
I have now 2 issues:
1)  I write some code to print an image after print a (long) zpl string (I don't write the value):

window.plugins.Base64.encodeFile("/mnt/sdcard/Pictures/logo.png", function(base64){
		base64StringArray.push(base64.substr(22));		
		cordova.plugins.zbtprinter.print(MACAddress, zpl,
				function(success) { 					
					cordova.plugins.zbtprinter.printImage(base64StringArray, MACAddress,
						function(success) { 							
							alert("print ok");							
						    }, function(fail) { 
							alert(fail); 
						    }
						);					
				}, function(fail) { 
					alert(fail); 
				}
			);
	},  function(fail) { 
		alert("fail encode"); 
	    }	
	);

But obtained only a start of printing, then the message:
"Printer is gepauzeerd. Gelieve deze eerst te activeren"

2) while printImage function stops after printed image, print function makes ribbon go further (more than 10 cm) instead of stopping after zpl executed. I don't know in advance how long is zpl output I printed... otherwise I would have utilized the ^LL instruction.

Thanks for your work!!

**Comment by prakashsatyani** [comment]
@ascattolini I see what issue you are facing. Here, instead of using 2 functions **printImage** and **print** what you can do is first convert your image base64 string into an equivalent ZPL code and then append this zpl code in your print text.

Try following code:

```
var base64Image     	= base64String;       //Your Image base64 string
var addHeaderFooter 	= false;    	      //want to add header/footer ZPL code or not
var blacknessPercentage = 50;		      //Image Blackness Percentage

cordova.plugins.zbtprinter.getZPLfromImage(base64Image, addHeaderFooter, blacknessPercentage,
    
    function(zplCode) {
        
       var printText = zpl;

       //Here append your "image ZPL" code at the end of your "actual ZPL" code
       printText = printText + zplCode;

      //After this use print command to print the combined ZPL
      cordova.plugins.zbtprinter.print(MACAddress, printText,
          function(success) { 
              alert("Print ok"); 
         }, function(error) { 
             alert(error); 
        });

   }, function(error) {
      alert(error);
   });
```
I have not added XS or XZ commands in above code for simplicity but you will need to take care of it.

You can set print size from the [Zebra Printer Setup Utility](https://play.google.com/store/apps/details?id=com.zebra.printersetup&hl=en) mobile app. 

If you use above method to print the images, the printer will not alter the previously set size. 


PS: I have changed all the error messages from Dutch to English now.
