### ISSUE TITLE
Thank you for providing such a great plugin

### ISSUE THREAD

**Issue by www3cc** [prakashsatyani/cordova-plugin-bluetooth-zbtprinter#2]
@prakashsatyani 

Thank you for providing such a great plugin

I want to ask about this plugin

Is it possible to add socket TCP/IP printing?

TCP/IP is also in line with printing mainstream

Hope the next version can add this feature

Thank you

**Comment by prakashsatyani** [comment]
@Mate20x Thank you for your kind words!!

Currently I am not focusing on this repository. However, in future I will try to upgrade the code base and add TCP/IP support as well :)
